---
title: "Indonesia regional wage"
output: html_document
---

```{r Import Library}
library(RDSTK)
library(dplyr)
library(leaflet)
```


```{r,echo=FALSE,comment=NA,results='hide'}
setwd("/Users/yogisharo/Documents/GitHub/indonesia-regional-wage-map/")
```

```{r Import Data}
wage_data <- read.csv("province_wage_data.csv", sep = ";")
location_data <- read.csv("province_latlong.csv", sep = ",")
```


```{r Data Cleaning}
wage_data <- wage_data %>%
  dplyr::filter(nama_tahun == 2016) %>%
  dplyr::select(province = nama_item_vertical_variabel,
                wage = data_content)



df <- wage_data %>%
  dplyr::left_join(location_data %>%
                     mutate(province = toupper(admin_name)) %>%
                     select(province, lat, lng),
                   by = "province") %>%
  group_by(province) %>%
  mutate(rank = row_number()) %>%
  ungroup() %>%
  dplyr::filter(rank == 1) %>% #remove duplicate from wage by regional city
  subset(province != "INDONESIA") %>% mutate(wage = as.numeric(wage)) # This is not the province
  
```


```{r map attributes & Visualization}
mybins <- seq(min(df$wage) * 0.9, max(df$wage) * 1.2, by = 500000) #create color spectrum
mypalette <- colorBin(
  palette = "YlOrBr",
  domain = df$wage,
  na.color = "transparent",
  bins = mybins
)

map = df %>%
  leaflet() %>%
  addTiles() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(
    ~ lng,
    ~ lat,
    fillColor = ~ mypalette(wage),
    fillOpacity = 0.7,
    color = "white",
    radius = 8,
    stroke = FALSE,
    label = ~ province,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "13px",
      direction = "auto"
    )
  ) %>%
  addMarkers(popup = paste0(df$province, ' : ',
                            paste(
                              'Rp', formatC(df$wage, big.mark = ',', format = 'fg') ## Add Rupiah Currency format
                            ))) %>%
  addLegend(
    "bottomleft", # Legend position
    pal = mypalette,  # color palette
    values =  ~ mybins,  # legend values
    opacity = 0.6,
    title = "Wage Range"
  )

map
```
